"""12-16-08

Revision ID: 0332e606bbc6
Revises: cb35bf799de9
Create Date: 2025-12-16 14:20:00.135936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0332e606bbc6'
down_revision: Union[str, Sequence[str], None] = 'cb35bf799de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'accounting_status',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'未入账'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'accounting_status',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'未入账'"))
    # ### end Alembic commands ###
