"""1-19-01

Revision ID: 066a12314b5c
Revises: d7d4452d4158
Create Date: 2026-01-19 14:01:36.097003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '066a12314b5c'
down_revision: Union[str, Sequence[str], None] = 'd7d4452d4158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('designer_withdraw_application_ibfk_1'), 'designer_withdraw_application', type_='foreignkey')
    op.drop_index(op.f('ix_finance_center_designer_id'), table_name='designer_withdraw_application')
    op.drop_index(op.f('ix_finance_center_payment_mode'), table_name='designer_withdraw_application')
    op.drop_index(op.f('ix_finance_center_payment_status'), table_name='designer_withdraw_application')
    op.drop_index(op.f('ix_finance_center_service_fee'), table_name='designer_withdraw_application')
    op.create_index(op.f('ix_designer_withdraw_application_applied_amount'), 'designer_withdraw_application', ['applied_amount'], unique=False)
    op.create_index(op.f('ix_designer_withdraw_application_apply_time'), 'designer_withdraw_application', ['apply_time'], unique=False)
    op.create_index(op.f('ix_designer_withdraw_application_payment_mode'), 'designer_withdraw_application', ['payment_mode'], unique=False)
    op.create_index(op.f('ix_designer_withdraw_application_payment_status'), 'designer_withdraw_application', ['payment_status'], unique=False)
    op.create_index(op.f('ix_designer_withdraw_application_service_fee'), 'designer_withdraw_application', ['service_fee'], unique=False)
    op.drop_table_comment(
        'designer_withdraw_application',
        existing_comment='设计师申请提现表',
        schema=None
    )
    op.drop_column('designer_withdraw_application', 'designer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_withdraw_application', sa.Column('designer_id', mysql.VARCHAR(length=100), nullable=False))
    op.create_table_comment(
        'designer_withdraw_application',
        '设计师申请提现表',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('designer_withdraw_application_ibfk_1'), 'designer_withdraw_application', 'designer_register_table', ['designer_id'], ['user_id'])
    op.drop_index(op.f('ix_designer_withdraw_application_service_fee'), table_name='designer_withdraw_application')
    op.drop_index(op.f('ix_designer_withdraw_application_payment_status'), table_name='designer_withdraw_application')
    op.drop_index(op.f('ix_designer_withdraw_application_payment_mode'), table_name='designer_withdraw_application')
    op.drop_index(op.f('ix_designer_withdraw_application_apply_time'), table_name='designer_withdraw_application')
    op.drop_index(op.f('ix_designer_withdraw_application_applied_amount'), table_name='designer_withdraw_application')
    op.create_index(op.f('ix_finance_center_service_fee'), 'designer_withdraw_application', ['service_fee'], unique=False)
    op.create_index(op.f('ix_finance_center_payment_status'), 'designer_withdraw_application', ['payment_status'], unique=False)
    op.create_index(op.f('ix_finance_center_payment_mode'), 'designer_withdraw_application', ['payment_mode'], unique=False)
    op.create_index(op.f('ix_finance_center_designer_id'), 'designer_withdraw_application', ['designer_id'], unique=True)
    # ### end Alembic commands ###
