"""1-11-02

Revision ID: 0b6609a15dad
Revises: fa18852cf419
Create Date: 2026-01-11 14:14:55.811989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6609a15dad'
down_revision: Union[str, Sequence[str], None] = 'fa18852cf419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_notification', sa.Column('order_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'order_notification', 'order_info', ['order_id'], ['order_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_notification', type_='foreignkey')
    op.drop_column('order_notification', 'order_id')
    # ### end Alembic commands ###
