"""1-8-01

Revision ID: 0cfac4cbc653
Revises: 00da8df0c638
Create Date: 2026-01-08 12:29:13.736353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfac4cbc653'
down_revision: Union[str, Sequence[str], None] = '00da8df0c638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works_table', sa.Column('works_status', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_works_table_works_status'), 'works_table', ['works_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_table_works_status'), table_name='works_table')
    op.drop_column('works_table', 'works_status')
    # ### end Alembic commands ###
