"""12_23_01

Revision ID: 2025
Revises: 5af797222b90
Create Date: 2025-12-23 13:13:15.410711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025'
down_revision: Union[str, Sequence[str], None] = '5af797222b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'finance_center', 'designer_register_table', ['designer_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_center', type_='foreignkey')
    # ### end Alembic commands ###
