"""changeTableBase

Revision ID: 2025_12_27_01
Revises: 2025
Create Date: 2025-12-27 13:50:54.272688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2025_12_27_01'
down_revision: Union[str, Sequence[str], None] = '2025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrator_info', 'user_avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('designer_register_table', 'user_avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'designer_register_table', ['user_avatar_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'designer_register_table', type_='unique')
    op.alter_column('designer_register_table', 'user_avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('administrator_info', 'user_avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
