"""12-16-05

Revision ID: 21e5a512c90b
Revises: 6151acce056e
Create Date: 2025-12-16 12:33:28.719217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21e5a512c90b'
down_revision: Union[str, Sequence[str], None] = '6151acce056e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'designer_register_table', ['id_card_no'])
    op.create_unique_constraint(None, 'designer_register_table', ['alipay_account'])
    op.create_unique_constraint(None, 'designer_register_table', ['bank_card_number'])
    op.create_index(op.f('ix_finance_center_service_fee'), 'finance_center', ['service_fee'], unique=False)
    op.create_index(op.f('ix_finance_center_status'), 'finance_center', ['status'], unique=False)
    op.create_index(op.f('ix_finance_center_withdrawal_application_no'), 'finance_center', ['withdrawal_application_no'], unique=True)
    op.create_index(op.f('ix_finance_center_withdrawal_method'), 'finance_center', ['withdrawal_method'], unique=False)
    op.drop_column('finance_center', 'related_order_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_center', sa.Column('related_order_ids', mysql.JSON(), server_default=sa.text('(json_array())'), nullable=False))
    op.drop_index(op.f('ix_finance_center_withdrawal_method'), table_name='finance_center')
    op.drop_index(op.f('ix_finance_center_withdrawal_application_no'), table_name='finance_center')
    op.drop_index(op.f('ix_finance_center_status'), table_name='finance_center')
    op.drop_index(op.f('ix_finance_center_service_fee'), table_name='finance_center')
    op.drop_constraint(None, 'designer_register_table', type_='unique')
    op.drop_constraint(None, 'designer_register_table', type_='unique')
    op.drop_constraint(None, 'designer_register_table', type_='unique')
    # ### end Alembic commands ###
