"""11-15-5

Revision ID: 2a11134b0ed2
Revises: af649919f327
Create Date: 2025-11-15 19:58:13.720577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a11134b0ed2'
down_revision: Union[str, Sequence[str], None] = 'af649919f327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrator_info', sa.Column('user_id2', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_administrator_info_user_id2'), 'administrator_info', ['user_id2'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administrator_info_user_id2'), table_name='administrator_info')
    op.drop_column('administrator_info', 'user_id2')
    # ### end Alembic commands ###
