"""add column overview and image_url

Revision ID: 315d6456aefd
Revises: 602c7c800e89
Create Date: 2025-11-07 12:45:36.959418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315d6456aefd'
down_revision: Union[str, Sequence[str], None] = '602c7c800e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('order_overview', sa.String(length=500), nullable=False))
    op.add_column('order_info', sa.Column('image_url', sa.String(length=1024), nullable=False))
    op.create_index(op.f('ix_order_info_image_url'), 'order_info', ['image_url'], unique=False)
    op.create_index(op.f('ix_order_info_order_overview'), 'order_info', ['order_overview'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_info_order_overview'), table_name='order_info')
    op.drop_index(op.f('ix_order_info_image_url'), table_name='order_info')
    op.drop_column('order_info', 'image_url')
    op.drop_column('order_info', 'order_overview')
    # ### end Alembic commands ###
