"""11-15-6

Revision ID: 343f714a1056
Revises: 2a11134b0ed2
Create Date: 2025-11-15 20:01:04.365770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '343f714a1056'
down_revision: Union[str, Sequence[str], None] = '2a11134b0ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administrator_info_user_id2'), table_name='administrator_info')
    op.drop_column('administrator_info', 'user_id2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrator_info', sa.Column('user_id2', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('ix_administrator_info_user_id2'), 'administrator_info', ['user_id2'], unique=True)
    # ### end Alembic commands ###
