"""1-12-01

Revision ID: 3523d30f616c
Revises: 0b6609a15dad
Create Date: 2026-01-12 13:43:13.229598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3523d30f616c'
down_revision: Union[str, Sequence[str], None] = '0b6609a15dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_notification', sa.Column('designer_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_order_notification_designer_id'), 'order_notification', ['designer_id'], unique=False)
    op.create_foreign_key(None, 'order_notification', 'designer_register_table', ['designer_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_notification', type_='foreignkey')
    op.drop_index(op.f('ix_order_notification_designer_id'), table_name='order_notification')
    op.drop_column('order_notification', 'designer_id')
    # ### end Alembic commands ###
