"""1-1-01

Revision ID: 363edcd7a2c2
Revises: f27ad15fdcd4
Create Date: 2026-01-01 15:32:36.504060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363edcd7a2c2'
down_revision: Union[str, Sequence[str], None] = 'f27ad15fdcd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works_table', sa.Column('download_permission', sa.Boolean(), nullable=False))
    op.add_column('works_table', sa.Column('visibility_status', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_works_table_download_permission'), 'works_table', ['download_permission'], unique=False)
    op.create_index(op.f('ix_works_table_visibility_status'), 'works_table', ['visibility_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_table_visibility_status'), table_name='works_table')
    op.drop_index(op.f('ix_works_table_download_permission'), table_name='works_table')
    op.drop_column('works_table', 'visibility_status')
    op.drop_column('works_table', 'download_permission')
    # ### end Alembic commands ###
