"""1-19-07

Revision ID: 38811e36bba0
Revises: 7b2e0d24efbc
Create Date: 2026-01-19 14:31:59.869344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38811e36bba0'
down_revision: Union[str, Sequence[str], None] = '7b2e0d24efbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('designer_withdraw_application_ibfk_1'), 'designer_withdraw_application', type_='foreignkey')
    op.alter_column('designer_withdraw_application', 'designer_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'designer_withdraw_application', 'designer_register_table', ['designer_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'designer_withdraw_application', type_='foreignkey')
    op.create_foreign_key(op.f('designer_withdraw_application_ibfk_1'), 'designer_withdraw_application', 'designer_register_table', ['designer_id'], ['user_id'], ondelete='SET NULL')
    op.alter_column('designer_withdraw_application', 'designer_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
