"""11-17-1

Revision ID: 3d4bab74ea06
Revises: 321cd82a3d1a
Create Date: 2025-11-17 12:14:29.198720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4bab74ea06'
down_revision: Union[str, Sequence[str], None] = '321cd82a3d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_register_table', sa.Column('designer_rating', sa.DECIMAL(precision=3, scale=2), server_default='4.50', nullable=False))
    op.add_column('designer_register_table', sa.Column('completed_orders', sa.String(length=100), server_default='0', nullable=False))
    op.create_index(op.f('ix_designer_register_table_completed_orders'), 'designer_register_table', ['completed_orders'], unique=False)
    op.create_index(op.f('ix_designer_register_table_designer_rating'), 'designer_register_table', ['designer_rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designer_register_table_designer_rating'), table_name='designer_register_table')
    op.drop_index(op.f('ix_designer_register_table_completed_orders'), table_name='designer_register_table')
    op.drop_column('designer_register_table', 'completed_orders')
    op.drop_column('designer_register_table', 'designer_rating')
    # ### end Alembic commands ###
