"""1-19-04

Revision ID: 3fc364401dbf
Revises: 7ef5325ad893
Create Date: 2026-01-19 14:23:08.011892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3fc364401dbf'
down_revision: Union[str, Sequence[str], None] = '7ef5325ad893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('designer_withdraw_application_ibfk_1'), 'designer_withdraw_application', type_='foreignkey')
    op.drop_index(op.f('designer_id'), table_name='designer_withdraw_application')
    op.drop_column('designer_withdraw_application', 'designer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_withdraw_application', sa.Column('designer_id', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key(op.f('designer_withdraw_application_ibfk_1'), 'designer_withdraw_application', 'designer_register_table', ['designer_id'], ['user_id'])
    op.create_index(op.f('designer_id'), 'designer_withdraw_application', ['designer_id'], unique=True)
    # ### end Alembic commands ###
