"""1-19-02

Revision ID: 457c9fdf0b4d
Revises: 066a12314b5c
Create Date: 2026-01-19 14:09:26.117686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457c9fdf0b4d'
down_revision: Union[str, Sequence[str], None] = '066a12314b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_withdraw_application', sa.Column('designer_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'designer_withdraw_application', ['designer_id'])
    op.create_foreign_key(None, 'designer_withdraw_application', 'designer_register_table', ['designer_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'designer_withdraw_application', type_='foreignkey')
    op.drop_constraint(None, 'designer_withdraw_application', type_='unique')
    op.drop_column('designer_withdraw_application', 'designer_id')
    # ### end Alembic commands ###
