"""add supervisor-3

Revision ID: 48cfda690c77
Revises: b7c065b18d71
Create Date: 2025-11-09 13:23:44.229204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48cfda690c77'
down_revision: Union[str, Sequence[str], None] = 'b7c065b18d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_info', 'supervisor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('supervisor_id', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
