"""12-21-02

Revision ID: 4ed195ee40b0
Revises: df8a32f9ebbf
Create Date: 2025-12-21 16:48:18.201251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ed195ee40b0'
down_revision: Union[str, Sequence[str], None] = 'df8a32f9ebbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finance_center', 'status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finance_center', 'status',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
