"""12-21-03

Revision ID: 4ff080c5dde6
Revises: 4ed195ee40b0
Create Date: 2025-12-21 16:55:53.558146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff080c5dde6'
down_revision: Union[str, Sequence[str], None] = '4ed195ee40b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_center', sa.Column('Payment_account', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'finance_center', ['Payment_account'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_center', type_='unique')
    op.drop_column('finance_center', 'Payment_account')
    # ### end Alembic commands ###
