"""11-16-1

Revision ID: 51e91c79cf40
Revises: 53de3b9433df
Create Date: 2025-11-16 14:45:25.965763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51e91c79cf40'
down_revision: Union[str, Sequence[str], None] = '53de3b9433df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_register_table', sa.Column('gender', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_designer_register_table_sex'), table_name='designer_register_table')
    op.create_index(op.f('ix_designer_register_table_gender'), 'designer_register_table', ['gender'], unique=False)
    op.drop_column('designer_register_table', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_register_table', sa.Column('sex', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_designer_register_table_gender'), table_name='designer_register_table')
    op.create_index(op.f('ix_designer_register_table_sex'), 'designer_register_table', ['sex'], unique=False)
    op.drop_column('designer_register_table', 'gender')
    # ### end Alembic commands ###
