"""1-8-04

Revision ID: 53b90fa26a9f
Revises: 006f9eef6125
Create Date: 2026-01-08 12:57:06.779768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53b90fa26a9f'
down_revision: Union[str, Sequence[str], None] = '006f9eef6125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works_table', sa.Column('works_status', mysql.TINYINT(), server_default='0', nullable=False, comment='0=待审核, 1=已发布, 2=已下架'))
    op.create_index(op.f('ix_works_table_works_status'), 'works_table', ['works_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_table_works_status'), table_name='works_table')
    op.drop_column('works_table', 'works_status')
    # ### end Alembic commands ###
