"""11-15-15

Revision ID: 53de3b9433df
Revises: f47a02fbb155
Create Date: 2025-11-15 21:20:35.743721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53de3b9433df'
down_revision: Union[str, Sequence[str], None] = 'f47a02fbb155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'supervisor_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'8620251115'"))
    op.drop_constraint(op.f('order_info_ibfk_1'), 'order_info', type_='foreignkey')
    op.create_foreign_key(None, 'order_info', 'administrator_info', ['supervisor_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_info', type_='foreignkey')
    op.create_foreign_key(op.f('order_info_ibfk_1'), 'order_info', 'administrator_info', ['supervisor_id'], ['user_id'])
    op.alter_column('order_info', 'supervisor_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'8620251115'"))
    # ### end Alembic commands ###
