"""add supervisor-4

Revision ID: 54bd42066596
Revises: 48cfda690c77
Create Date: 2025-11-09 13:25:20.832154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bd42066596'
down_revision: Union[str, Sequence[str], None] = '48cfda690c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('supervisor_id', sa.String(length=100), server_default='8620251024', nullable=False))
    op.create_foreign_key(None, 'order_info', 'administrator_info', ['supervisor_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_info', type_='foreignkey')
    op.drop_column('order_info', 'supervisor_id')
    # ### end Alembic commands ###
