"""12-22-01

Revision ID: 5af797222b90
Revises: 6b6b7329252e
Create Date: 2025-12-22 15:32:50.554047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5af797222b90'
down_revision: Union[str, Sequence[str], None] = '6b6b7329252e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_center', sa.Column('payment_status', mssql.TINYINT(), server_default='0', nullable=False, comment='0=申请中,1=已打款,驳回'))
    op.drop_index(op.f('ix_finance_center_status'), table_name='finance_center')
    op.create_index(op.f('ix_finance_center_payment_status'), 'finance_center', ['payment_status'], unique=False)
    op.drop_column('finance_center', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_center', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_finance_center_payment_status'), table_name='finance_center')
    op.create_index(op.f('ix_finance_center_status'), 'finance_center', ['status'], unique=False)
    op.drop_column('finance_center', 'payment_status')
    # ### end Alembic commands ###
