"""delete customer column

Revision ID: 602c7c800e89
Revises: 
Create Date: 2025-11-06 12:25:01.620492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '602c7c800e89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrator_info', 'user_password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_age'), table_name='administrator_info')
    op.drop_index(op.f('idx_name'), table_name='administrator_info')
    op.drop_index(op.f('idx_registration_date'), table_name='administrator_info')
    op.drop_index(op.f('idx_user_password'), table_name='administrator_info')
    op.drop_index(op.f('ix_order_info_customer_name'), table_name='order_info')
    op.drop_column('order_info', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('customer_name', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('ix_order_info_customer_name'), 'order_info', ['customer_name'], unique=False)
    op.create_index(op.f('idx_user_password'), 'administrator_info', ['user_password'], unique=False)
    op.create_index(op.f('idx_registration_date'), 'administrator_info', ['registration_date'], unique=False)
    op.create_index(op.f('idx_name'), 'administrator_info', ['name'], unique=False)
    op.create_index(op.f('idx_age'), 'administrator_info', ['age'], unique=False)
    op.alter_column('administrator_info', 'user_password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
