"""12-15-01

Revision ID: 6151acce056e
Revises: 85e4662e4844
Create Date: 2025-12-15 15:30:48.186358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6151acce056e'
down_revision: Union[str, Sequence[str], None] = '85e4662e4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_account_table_base', sa.Column('id_card_no', sa.String(length=100), server_default='', nullable=False))
    op.create_index(op.f('ix_designer_account_table_base_id_card_no'), 'designer_account_table_base', ['id_card_no'], unique=False)
    op.create_index(op.f('ix_designer_account_table_base_total_income'), 'designer_account_table_base', ['total_income'], unique=False)
    op.create_index(op.f('ix_finance_center_service_fee'), 'finance_center', ['service_fee'], unique=False)
    op.create_index(op.f('ix_finance_center_status'), 'finance_center', ['status'], unique=False)
    op.create_index(op.f('ix_finance_center_withdrawal_application_no'), 'finance_center', ['withdrawal_application_no'], unique=True)
    op.create_index(op.f('ix_finance_center_withdrawal_method'), 'finance_center', ['withdrawal_method'], unique=False)
    op.drop_column('finance_center', 'related_order_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_center', sa.Column('related_order_ids', mysql.JSON(), server_default=sa.text('(json_array())'), nullable=False))
    op.drop_index(op.f('ix_finance_center_withdrawal_method'), table_name='finance_center')
    op.drop_index(op.f('ix_finance_center_withdrawal_application_no'), table_name='finance_center')
    op.drop_index(op.f('ix_finance_center_status'), table_name='finance_center')
    op.drop_index(op.f('ix_finance_center_service_fee'), table_name='finance_center')
    op.drop_index(op.f('ix_designer_account_table_base_total_income'), table_name='designer_account_table_base')
    op.drop_index(op.f('ix_designer_account_table_base_id_card_no'), table_name='designer_account_table_base')
    op.drop_column('designer_account_table_base', 'id_card_no')
    # ### end Alembic commands ###
