"""12-21-05

Revision ID: 6b6b7329252e
Revises: a749b39e4eb4
Create Date: 2025-12-21 17:02:49.618017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6b7329252e'
down_revision: Union[str, Sequence[str], None] = 'a749b39e4eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_center', sa.Column('payment_account', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'finance_center', ['payment_account'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_center', type_='unique')
    op.drop_column('finance_center', 'payment_account')
    # ### end Alembic commands ###
