"""1-19-06

Revision ID: 7b2e0d24efbc
Revises: dad8073537e9
Create Date: 2026-01-19 14:30:47.537787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2e0d24efbc'
down_revision: Union[str, Sequence[str], None] = 'dad8073537e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_withdraw_application', sa.Column('designer_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_designer_withdraw_application_designer_id'), 'designer_withdraw_application', ['designer_id'], unique=False)
    op.create_foreign_key(None, 'designer_withdraw_application', 'designer_register_table', ['designer_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'designer_withdraw_application', type_='foreignkey')
    op.drop_index(op.f('ix_designer_withdraw_application_designer_id'), table_name='designer_withdraw_application')
    op.drop_column('designer_withdraw_application', 'designer_id')
    # ### end Alembic commands ###
