"""11-8

Revision ID: 831b5072b0aa
Revises: e2db076e9183
Create Date: 2025-11-08 16:47:03.734369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '831b5072b0aa'
down_revision: Union[str, Sequence[str], None] = 'e2db076e9183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('delivery_deadline', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_order_info_image_url'), table_name='order_info')
    op.create_index(op.f('ix_order_info_delivery_deadline'), 'order_info', ['delivery_deadline'], unique=False)
    op.drop_column('order_info', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('image_url', mysql.VARCHAR(length=1024), nullable=False))
    op.drop_index(op.f('ix_order_info_delivery_deadline'), table_name='order_info')
    op.create_index(op.f('ix_order_info_image_url'), 'order_info', ['image_url'], unique=False)
    op.drop_column('order_info', 'delivery_deadline')
    # ### end Alembic commands ###
