"""11-23-1

Revision ID: 85e4662e4844
Revises: f3d8c54499b0
Create Date: 2025-11-23 17:41:03.943577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e4662e4844'
down_revision: Union[str, Sequence[str], None] = 'f3d8c54499b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_register_table', sa.Column('on_line_status', sa.Boolean(), server_default='0', nullable=False))
    op.create_index(op.f('ix_designer_register_table_on_line_status'), 'designer_register_table', ['on_line_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designer_register_table_on_line_status'), table_name='designer_register_table')
    op.drop_column('designer_register_table', 'on_line_status')
    # ### end Alembic commands ###
