"""11-15-13

Revision ID: 8fd53cc83c95
Revises: 55c957089ae6
Create Date: 2025-11-15 21:00:21.186186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd53cc83c95'
down_revision: Union[str, Sequence[str], None] = '55c957089ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrator_info', sa.Column('user_id2', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'administrator_info', ['user_id2'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'administrator_info', type_='unique')
    op.drop_column('administrator_info', 'user_id2')
    # ### end Alembic commands ###
