"""11-20-1

Revision ID: 9114aa1f0989
Revises: 3d4bab74ea06
Create Date: 2025-11-20 12:54:43.902401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9114aa1f0989'
down_revision: Union[str, Sequence[str], None] = '3d4bab74ea06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_info', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('user_id', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=True))
    # ### end Alembic commands ###
