"""add supervisor-1

Revision ID: 9745a0431b7b
Revises: afe6d409ed18
Create Date: 2025-11-09 13:14:41.534422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9745a0431b7b'
down_revision: Union[str, Sequence[str], None] = 'afe6d409ed18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'supervisor_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_foreign_key(None, 'order_info', 'administrator_info', ['supervisor_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_info', type_='foreignkey')
    op.alter_column('order_info', 'supervisor_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
