"""11-22-1

Revision ID: 9e25d4638208
Revises: 1f1daef4247f
Create Date: 2025-11-22 13:17:59.610141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e25d4638208'
down_revision: Union[str, Sequence[str], None] = '1f1daef4247f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('designer_id', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('order_info_ibfk_2'), 'order_info', type_='foreignkey')
    op.create_foreign_key(None, 'order_info', 'designer_register_table', ['designer_id'], ['user_id'], ondelete='SET NULL')
    op.drop_column('order_info', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('user_id', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'order_info', type_='foreignkey')
    op.create_foreign_key(op.f('order_info_ibfk_2'), 'order_info', 'designer_register_table', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.drop_column('order_info', 'designer_id')
    # ### end Alembic commands ###
