"""12-21-04

Revision ID: a749b39e4eb4
Revises: 4ff080c5dde6
Create Date: 2025-12-21 17:02:30.730327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a749b39e4eb4'
down_revision: Union[str, Sequence[str], None] = '4ff080c5dde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('Payment_account'), table_name='finance_center')
    op.drop_column('finance_center', 'Payment_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_center', sa.Column('Payment_account', mysql.VARCHAR(length=255), nullable=False))
    op.create_index(op.f('Payment_account'), 'finance_center', ['Payment_account'], unique=True)
    # ### end Alembic commands ###
