"""add supervisor

Revision ID: afe6d409ed18
Revises: 7e6e641ab0e9
Create Date: 2025-11-09 12:27:44.575619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe6d409ed18'
down_revision: Union[str, Sequence[str], None] = '7e6e641ab0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('supervisor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_info', 'administrator_info', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_info', type_='foreignkey')
    op.drop_column('order_info', 'supervisor_id')
    # ### end Alembic commands ###
