"""add supervisor-2

Revision ID: b7c065b18d71
Revises: 9745a0431b7b
Create Date: 2025-11-09 13:18:43.721094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7c065b18d71'
down_revision: Union[str, Sequence[str], None] = '9745a0431b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_info', 'supervisor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('supervisor_id', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
