"""chenge amount mofify

Revision ID: b7f3bedf83f7
Revises: 54bd42066596
Create Date: 2025-11-10 11:02:46.355362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7f3bedf83f7'
down_revision: Union[str, Sequence[str], None] = '54bd42066596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'amount',
               existing_type=mysql.DECIMAL(precision=65, scale=1),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'amount',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=65, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###
