"""12-16-06

Revision ID: cb35bf799de9
Revises: 21e5a512c90b
Create Date: 2025-12-16 13:40:05.465741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb35bf799de9'
down_revision: Union[str, Sequence[str], None] = '21e5a512c90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('accounting_status', sa.String(length=5), server_default='未入账', nullable=False))
    op.create_index(op.f('ix_order_info_accounting_status'), 'order_info', ['accounting_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_info_accounting_status'), table_name='order_info')
    op.drop_column('order_info', 'accounting_status')
    # ### end Alembic commands ###
