"""11-20-2

Revision ID: cf5dd440035d
Revises: 9114aa1f0989
Create Date: 2025-11-20 12:56:21.074025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5dd440035d'
down_revision: Union[str, Sequence[str], None] = '9114aa1f0989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'order_info', 'designer_register_table', ['user_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_info', type_='foreignkey')
    op.drop_column('order_info', 'user_id')
    # ### end Alembic commands ###
