"""12-16-11

Revision ID: d9ff9352896e
Revises: 0332e606bbc6
Create Date: 2025-12-16 14:50:36.871974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9ff9352896e'
down_revision: Union[str, Sequence[str], None] = '0332e606bbc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'accounting_status',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'accounting_status',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'未入账'"))
    # ### end Alembic commands ###
