"""12-21-01

Revision ID: df8a32f9ebbf
Revises: d9ff9352896e
Create Date: 2025-12-21 16:43:39.219044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df8a32f9ebbf'
down_revision: Union[str, Sequence[str], None] = 'd9ff9352896e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designer_account_table_base_designer_Id'), table_name='designer_account_table_base')
    op.create_index(op.f('ix_designer_account_table_base_designer_id'), 'designer_account_table_base', ['designer_id'], unique=False)
    op.add_column('finance_center', sa.Column('designer_id', sa.String(length=255), nullable=False))
    op.add_column('finance_center', sa.Column('applied_amount', sa.DECIMAL(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('finance_center', sa.Column('payment_mode', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_finance_center_withdrawal_amount'), table_name='finance_center')
    op.drop_index(op.f('ix_finance_center_withdrawal_method'), table_name='finance_center')
    op.create_index(op.f('ix_finance_center_applied_amount'), 'finance_center', ['applied_amount'], unique=False)
    op.create_index(op.f('ix_finance_center_designer_id'), 'finance_center', ['designer_id'], unique=True)
    op.create_index(op.f('ix_finance_center_payment_mode'), 'finance_center', ['payment_mode'], unique=False)
    op.drop_column('finance_center', 'withdrawal_amount')
    op.drop_column('finance_center', 'withdrawal_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_center', sa.Column('withdrawal_method', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('finance_center', sa.Column('withdrawal_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_index(op.f('ix_finance_center_payment_mode'), table_name='finance_center')
    op.drop_index(op.f('ix_finance_center_designer_id'), table_name='finance_center')
    op.drop_index(op.f('ix_finance_center_applied_amount'), table_name='finance_center')
    op.create_index(op.f('ix_finance_center_withdrawal_method'), 'finance_center', ['withdrawal_method'], unique=False)
    op.create_index(op.f('ix_finance_center_withdrawal_amount'), 'finance_center', ['withdrawal_amount'], unique=False)
    op.drop_column('finance_center', 'payment_mode')
    op.drop_column('finance_center', 'applied_amount')
    op.drop_column('finance_center', 'designer_id')
    op.drop_index(op.f('ix_designer_account_table_base_designer_id'), table_name='designer_account_table_base')
    op.create_index(op.f('ix_designer_account_table_base_designer_Id'), 'designer_account_table_base', ['designer_id'], unique=False)
    # ### end Alembic commands ###
