"""1-19-08

Revision ID: e8137c373b6a
Revises: 38811e36bba0
Create Date: 2026-01-19 14:41:49.978641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e8137c373b6a'
down_revision: Union[str, Sequence[str], None] = '38811e36bba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('designer_withdraw_application_ibfk_1'), 'designer_withdraw_application', type_='foreignkey')
    op.drop_index(op.f('ix_designer_withdraw_application_designer_id'), table_name='designer_withdraw_application')
    op.drop_column('designer_withdraw_application', 'designer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer_withdraw_application', sa.Column('designer_id', mysql.VARCHAR(length=100), nullable=False))
    op.create_foreign_key(op.f('designer_withdraw_application_ibfk_1'), 'designer_withdraw_application', 'designer_register_table', ['designer_id'], ['user_id'])
    op.create_index(op.f('ix_designer_withdraw_application_designer_id'), 'designer_withdraw_application', ['designer_id'], unique=False)
    # ### end Alembic commands ###
