"""12-29-01

Revision ID: f27ad15fdcd4
Revises: 2025_12_27_01
Create Date: 2025-12-29 19:02:15.169159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27ad15fdcd4'
down_revision: Union[str, Sequence[str], None] = '2025_12_27_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works_image_table', sa.Column('sort_num', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_works_image_table_sort_num'), 'works_image_table', ['sort_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_image_table_sort_num'), table_name='works_image_table')
    op.drop_column('works_image_table', 'sort_num')
    # ### end Alembic commands ###
