"""11-22-2

Revision ID: f3d8c54499b0
Revises: 9e25d4638208
Create Date: 2025-11-22 18:22:09.062226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d8c54499b0'
down_revision: Union[str, Sequence[str], None] = '9e25d4638208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrator_info', sa.Column('user_role', sa.String(length=255), server_default='admin', nullable=False))
    op.create_index(op.f('ix_administrator_info_user_role'), 'administrator_info', ['user_role'], unique=False)
    op.add_column('designer_register_table', sa.Column('user_role', sa.String(length=255), server_default='designer', nullable=False))
    op.create_index(op.f('ix_designer_register_table_user_role'), 'designer_register_table', ['user_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designer_register_table_user_role'), table_name='designer_register_table')
    op.drop_column('designer_register_table', 'user_role')
    op.drop_index(op.f('ix_administrator_info_user_role'), table_name='administrator_info')
    op.drop_column('administrator_info', 'user_role')
    # ### end Alembic commands ###
