"""1-11-01

Revision ID: fa18852cf419
Revises: d447d4cca522
Create Date: 2026-01-11 13:58:34.390632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa18852cf419'
down_revision: Union[str, Sequence[str], None] = 'd447d4cca522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_notifications_delivery_status'), table_name='order_notifications')
    op.drop_index(op.f('ix_order_notifications_is_read'), table_name='order_notifications')
    op.drop_index(op.f('ix_order_notifications_notification'), table_name='order_notifications')
    op.drop_index(op.f('ix_order_notifications_sent_at'), table_name='order_notifications')
    op.drop_table('order_notifications')
    op.add_column('order_notification', sa.Column('notification', sa.String(length=255), nullable=False))
    op.add_column('order_notification', sa.Column('delivery_status', mysql.TINYINT(), nullable=False, comment='0=已推送, 1=用户已加载'))
    op.add_column('order_notification', sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('order_notification', sa.Column('sent_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_order_notification_notification_id'), table_name='order_notification')
    op.create_index(op.f('ix_order_notification_delivery_status'), 'order_notification', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_order_notification_is_read'), 'order_notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_order_notification_notification'), 'order_notification', ['notification'], unique=False)
    op.create_index(op.f('ix_order_notification_sent_at'), 'order_notification', ['sent_at'], unique=False)
    op.drop_column('order_notification', 'notification_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_notification', sa.Column('notification_id', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_order_notification_sent_at'), table_name='order_notification')
    op.drop_index(op.f('ix_order_notification_notification'), table_name='order_notification')
    op.drop_index(op.f('ix_order_notification_is_read'), table_name='order_notification')
    op.drop_index(op.f('ix_order_notification_delivery_status'), table_name='order_notification')
    op.create_index(op.f('ix_order_notification_notification_id'), 'order_notification', ['notification_id'], unique=False)
    op.drop_column('order_notification', 'sent_at')
    op.drop_column('order_notification', 'is_read')
    op.drop_column('order_notification', 'delivery_status')
    op.drop_column('order_notification', 'notification')
    op.create_table('order_notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notification', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('delivery_status', mysql.TINYINT(), autoincrement=False, nullable=False, comment='0=已推送, 1=用户已加载'),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('sent_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_order_notifications_sent_at'), 'order_notifications', ['sent_at'], unique=False)
    op.create_index(op.f('ix_order_notifications_notification'), 'order_notifications', ['notification'], unique=False)
    op.create_index(op.f('ix_order_notifications_is_read'), 'order_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_order_notifications_delivery_status'), 'order_notifications', ['delivery_status'], unique=False)
    # ### end Alembic commands ###
